name: Audit

on:
  push:
    tags:
      - "*"

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    
    - name: Go modules Cache # Docs: <https://git.io/JfAKn#go---modules>
      uses: actions/cache@v4
      id: go-cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - if: steps.go-cache.outputs.cache-hit != 'true'
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    - name: Build binaries
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o "vk-cli-linux-amd64"
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o "vk-cli-linux-arm64"
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o "vk-cli-windows-amd64.exe"

    - name: ls
      run: ls -l

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vk-cli-*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
